build_from:
  aarch64: ghcr.io/hassio-addons/base:14.2.2
  amd64: ghcr.io/hassio-addons/base:14.2.2
args:
  DDNSTO_VERSION: 3.0.5
# codenotary:
#   base_image: codenotary@frenck.dev
#   signer: tom.czhen@gmail.com