name: "DDNSTO"
slug: ddnsto
version: "3.0.5"
description: "DDNSTO 是一款稳定、快速、简单易用的内网穿透工具"
url: https://github.com/TomCzHen/ddnsto-hassio
codenotary: tom.czhen@gmail.com
startup: services
init: false
apparmor: false
arch:
  - aarch64
  - amd64
host_network: true
options:
  user_token:
  device_id: 0
schema:
  user_token: match([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})
  device_id: list(0|1|2|3|4|5|6|7|8|9)
image: "tomczhen/ddnsto-hassio-{arch}"